### PR TITLE
fix(lookup, formvuelate): remapped nested

### LINKED ISSUE #252: Console warning with locally imported components
**Describe the bug**
When using [locally imported components as strings](https://formvuelate.js.org/guide/plugins.html#using-locally-imported-components), an unnecessary(?) warning is shown on the console.

**To Reproduce**
1. Visit: https://codesandbox.io/s/fvl-local-imports-forked-hjb31
2. View the console to see `[Vue warn]: injection "fvl_injectedLocalComponents" not found."`

**Expected behavior**
- Warning should be suppressed?

**System Info**
- FormVueLate version: 3.7.1

### PR DESCRIPTION
**Pull request by marina-mosti**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/formvuelate/formvuelate/blob/main/.github/CONTRIBUTING.md#development-setup
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

When using `lookupSubSchemas` and mapProps/mapComponents at the same time a race condition happened.
Due to the lookupSubSchemas parsing function being called at ParsedSchema.js level, it silently "skipped" it if the component property was not found.

This required refactoring the approach into Lookup providing the actual function that needs to be executed when this happens, so that we can eagerly call it on ParsedSchema.js for scenarios where `lookupSubSchemas` is used _without_ the LookupPlugin being added to the plugin stack AND scenarios where the plugin is also added.

E2e tests have been added with scenarios to replicate the problem.

### CODE REVIEW

File: packages/formvuelate/src/SchemaForm.vue [hunk 1]
```diff
@@ -68,7 +70,8 @@ export default {
     useCustomFormWrapper: {
       type: Boolean,
       default: false
-    }
+    },
+    debug: { type: Boolean, default: false }
```
Comment (logaretm) [inline packages/formvuelate/src/SchemaForm.vue:74]: Maybe for the future but we could drop this in non-es/unminified bundles with compilation flags to avoid people leaking this to their production.

**Review by logaretm — APPROVED** [review]
Nice work 👍
